 export const Logos = [
    {
        id:1,
        img:'./assets/langauge/react.png',
        name:'React'
    },
    {
        id:2,
        img:'./assets/langauge/javascripts.png',
        name:'JavaScript'
    },
    {
        id:3,
        img:'./assets/langauge/html.png',
        name:'HTML'
    },
    {
        id:4,
        img:'./assets/langauge/css.png',
        name:'CSS'
    },
    {
        id:5,
        img:'./assets/langauge/bootstrap.png',
        name:'Bootstrap'
    },
    {
        id:6,
        img:'./assets/langauge/Tailwind CSS.png',
        name:'Tailwind'
    },
    {
        id:7,
        img:'./assets/langauge/nodejs.png',
        name:'Node.JS'
    },
    {
        id:8,
        img:'./assets/langauge/express.png',
        name:'Express.JS'
    },
    {
        id:9,
        img:'./assets/langauge/mongo.png',
        name:'MongoDB'
    }
];